JobPortal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('JobWork.urls')),
    path('', include('AccountsUser.urls')),
]

JobWork/urls.py
from django.urls import path, include
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = "JobWork"

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about', home.about,name='About'),
    path('contact', home.contact,name='Contact'),
    path('intro', home.intro,name='Intro'),
    path('search', SearchView.as_view(), name='searh'),
    path('employer/dashboard', include([
        path('', DashboardView.as_view(), name='employer-dashboard'),
        path('applicants/<int:job_id>', ApplicantPerJobView.as_view(), name='employer-dashboard-applicants'),
        path('delete/<int:job_id>/', delete_view, name='employer-dashboard-delete'),

    ])),
    path('apply-job/<int:job_id>', ApplyJobView.as_view(), name='apply-job'),
    path('jobs/<int:id>', JobDetailsView.as_view(), name='jobs-detail'),
    path('employer/jobs/create', JobCreateView.as_view(), name='employer-jobs-create'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

JobWork/views/employer.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView
from django.shortcuts import render, get_object_or_404, redirect

from JobWork.decorators import user_is_employer
from JobWork.forms import CreateJobForm
from JobWork.models import Job, Applicant

class DashboardView(ListView):
###view for company dashboard
    model = Job
    template_name = 'jobs/employer/dashboard.html'
    context_object_name = 'jobs'

    @method_decorator(login_required(login_url=reverse_lazy('AccountsUser:login')))
    @method_decorator(user_is_employer)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):
        return self.model.objects.filter(user_id=self.request.user.id)


class ApplicantPerJobView(ListView):
###view to show applicants per job
    model = Applicant
    template_name = 'jobs/employer/applicants.html'
    context_object_name = 'applicants'
    paginate_by = 1

    @method_decorator(login_required(login_url=reverse_lazy('AccountsUser:login')))
    @method_decorator(user_is_employer)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):
        return Applicant.objects.filter(job_id=self.kwargs['job_id']).order_by('id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['job'] = Job.objects.get(id=self.kwargs['job_id'])
        return context


class JobCreateView(CreateView):
###view to create job post
    form_class = CreateJobForm
    template_name = 'jobs/create.html'
    success_url = reverse_lazy('JobWork:employer-dashboard')

    @method_decorator(login_required(login_url=reverse_lazy('AccountsUser:login')))
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return reverse_lazy('AccountsUser:login')
        if self.request.user.is_authenticated and self.request.user.role != 'employer':
            return reverse_lazy('AccountsUser:login')
        return super().dispatch(self.request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(JobCreateView, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        self.object = None   
        form = self.get_form()
        if form.is_valid():
            messages.info(request, 'Job Created Successfully!!!')
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


def delete_view(request, job_id):
###to delete job post
    context ={}
    obj = get_object_or_404(Job, id = job_id)
    if request.method =="POST":
        obj.delete()
        messages.success(request, 'Your Job Post was successfully deleted!')
        return redirect('JobWork:employer-dashboard')
    return render(request, "jobs/employer/delete.html", context)

templates/jobs/employer/applicants.html
{% extends 'base.html' %}
{% block title %}
    Applicants
{% endblock %}
{% load static %}

{% block content %}
    <section class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h1 class="heading">Applicants for the <span class="accent">{{ job.title }}</span> Position</h1>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <div class="row">
                {% for applicant in applicants %}
                    <div class="col-lg-6 offset-3">
                        <div class="box applicant">
                            <h4><font color="black">{{ applicant.user.get_full_name }}</font></h4>
                            <p><i class="fa fa-envelope"></i> {{ applicant.user.email }}</p>
                            <p>Applied {{ applicant.created_at.astimezone }}</p>
                            <div class="col-lg-3 mx-0 px-0">
                                <img src="{% static 'img/7.png' %}" widht=100 height=100 alt="" class="img-fluid rounded-circle">
                            </div>
                            <a href="{{applicant.user.pdf.url}}" class="btn btn-secondary btn-sm"><i class="fa fa-file"> Resume</i>
                            </a>
                        </div>
                {% endfor %}

                <!--for pagination so that all applicant display on different pages-->
                {% if is_paginated %}
                            <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-4 mb-4">
                                <ul class="pagination">
                                    {% if page_obj.has_previous %}
                                        <li class="page-item">
                                            <a href="?page={{ page_obj.previous_page_number }}"
                                               class="page-link">&laquo;</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled">
                                            <a class="page-link">&laquo;</a>
                                        </li>
                                    {% endif %}
                                    {% for i in page_obj.paginator.page_range %}
                                        {% if page_obj.number == i %}
                                            <li class="page-item active">
                                                <a class="page-link">{{ i }}</a>
                                            </li>
                                        {% else %}
                                            <li class="page-item">
                                                <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                                            </li>
                                        {% endif %}
                                    {% endfor %}
                                    {% if page_obj.has_next %}
                                        <li class="page-item">
                                            <a href="?page={{ page_obj.next_page_number }}"
                                               class="page-link">&raquo;</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled">
                                            <a class="page-link">&raquo;</a>
                                        </li>
                                    {% endif %}
                                </ul>
                            </nav>
                    </div>
                {% else %}
                    <h3 class="text-center">No Applicants To Show!!!</h3>
                {% endif %}
            </div>
        </div>
    </section>

{% endblock %}

templates/jobs/employer/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Dashboard
{% endblock %}

{% block content %}

    <section class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h1 class="heading">Dashboard</h1>
                    <p class="lead text-center">All created Jobs</p>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-right mb-5"><a href="{% url 'JobWork:employer-jobs-create' %}" class="btn btn-dark">
                    <i class="fa fa-plus"></i> Add New Job</a></div>
                
                <!--Creating table for displaying all the details of jobs created by company-->
                <div class="col-lg-12">
                    <div class="table-responsive">
                        <table class="table table-striped table-hover table-client-dashboard">
                            <thead>
                            <tr>
                                <th>Job title</th>
                                <th>Date posted</th>
                                <th>Date expiring</th>
                                <th>Applicants</th>
                                <th>Delete Job</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for job in jobs %}
                            <!--table creation for displaying the job and applicants details-->
                                <tr>
                                    <th><a href="{% url 'JobWork:jobs-detail' job.id %}">{{ job.title }}</a>
                                    </th>
                                    <td>{{ job.created_at|date }}</td>
                                    <td>{{ job.last_date|date }}</td>                                    
                                    <td>
                                        <a href="{% url 'JobWork:employer-dashboard-applicants' job.id %}" class="btn btn-success">
                                            <i class="fa fa-users"></i>{{ job.applicants.count }}
                                            <span class="hidden-xs hidden-sm">Applicants</span>
                                        </a>
                                    </td>
                                    <td>    
                                        <a href="{% url 'JobWork:employer-dashboard-delete' job.id %}" class="btn btn-danger">
                                            <i class="fa fa-times-circle-o"></i> Delete
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/jobs/employer/delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Delete Job
{% endblock %}

{% block content %}
<section class="bg-light-gray">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto">
                <form method="post">
                    {% csrf_token %}
                    <h1 class="heading">Are you sure you want to delete Job?</h1>
                    <input type="submit" value="Confirm" class="btn btn-dark col-lg-12 mt-2 mb-5">
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock %}