AccountsUser/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from JobWork.views import EditProfileView
from .views import *

app_name = "AccountsUser"

urlpatterns = [
    path('employee/register', RegisterEmployeeView.as_view(), name='employee-register'),
    path('employer/register', RegisterEmployerView.as_view(), name='employer-register'),
    path('employee/profile/update', EditProfileView.as_view(), name='employer-profile-update'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('login', LoginView.as_view(), name='login'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

JobPortal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('JobWork.urls')),
    path('', include('AccountsUser.urls')),
]

JobWork/urls.py
from django.urls import path, include
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = "JobWork"

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about', home.about,name='About'),
    path('contact', home.contact,name='Contact'),
    path('intro', home.intro,name='Intro'),
    path('search', SearchView.as_view(), name='searh'),
    path('employer/dashboard', include([
        path('', DashboardView.as_view(), name='employer-dashboard'),
        path('applicants/<int:job_id>', ApplicantPerJobView.as_view(), name='employer-dashboard-applicants'),
        path('delete/<int:job_id>/', delete_view, name='employer-dashboard-delete'),

    ])),
    path('apply-job/<int:job_id>', ApplyJobView.as_view(), name='apply-job'),
    path('jobs/<int:id>', JobDetailsView.as_view(), name='jobs-detail'),
    path('employer/jobs/create', JobCreateView.as_view(), name='employer-jobs-create'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

JobWork/views/home.py
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, CreateView

from JobWork.forms import ApplyJobForm
from JobWork.models import Job, Applicant, Contact


class HomeView(ListView):
###view for home 
    model = Job
    template_name = 'home.html'
    context_object_name = 'jobs'

    def get_queryset(self):
        return self.model.objects.all()[:6]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['trendings'] = self.model.objects.filter(created_at__month=timezone.now().month)[:3]
        return context


class SearchView(ListView):
###view for searching the jobs
    model = Job
    template_name = 'jobs/search.html'
    context_object_name = 'jobs'

    def get_queryset(self):
        return self.model.objects.filter(location__contains=self.request.GET['location'],
                                         title__contains=self.request.GET['position'])


class JobDetailsView(DetailView):
###to show the details of the job
    model = Job
    template_name = 'jobs/details.html'
    context_object_name = 'job'
    pk_url_kwarg = 'id'

    def get_object(self, queryset=None):
        obj = super(JobDetailsView, self).get_object(queryset=queryset)
        if obj is None:
            raise Http404("Job doesn't exists")
        return obj

    def get(self, request, *args, **kwargs):
        try:
            self.object = self.get_object()
        except Http404:
            raise Http404("Job doesn't exists")
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)


class ApplyJobView(CreateView):
###to apply for the job
    model = Applicant
    form_class = ApplyJobForm
    slug_field = 'job_id'
    slug_url_kwarg = 'job_id'

    @method_decorator(login_required(login_url=reverse_lazy('AccountsUser:login')))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            messages.info(self.request, 'Successfully applied for the job!')
            return self.form_valid(form)
        else:
            return HttpResponseRedirect(reverse_lazy('JobWork:home'))

    def get_success_url(self):
        return reverse_lazy('JobWork:jobs-detail', kwargs={'id': self.kwargs['job_id']})


    def form_valid(self, form):
        ### check if user already applied
        applicant = Applicant.objects.filter(user_id=self.request.user.id, job_id=self.kwargs['job_id'])
        if applicant:
            messages.info(self.request, 'You already applied for this job')
            return HttpResponseRedirect(self.get_success_url())
        form.instance.user = self.request.user
        form.save()
        return super().form_valid(form)


def about(request):
###about function for displaying about jobs
    return render(request,'about.html')


def contact(request):
###contact function for contacting the admin of website
    if request.method == "POST":
        name = request.POST.get('name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        desc = request.POST.get('desc')
        contact = Contact(name=name, email=email, phone=phone, desc=desc)
        contact.save()
        messages.success(request, 'Your message has been sent!!')
    return render(request, 'contact.html')


def intro(request):
###intro function for displaying intro details.
    return render(request,'intro.html')

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}About{% endblock %}

{% block content %}
<!--use of carousel from bootstrap-->
<div id="carouselExampleCaptions" class="carousel  slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'img/2.jpg' %}" width=200 height=300 class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static 'img/3.jpg' %}" width=200 height=300 class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static 'img/4.jpg' %}" width=200 height=300 class="d-block w-100" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

<!--making section for creating display attractive and use of albums from bootstrap-->
<section class="bg-success">
    <div class="container text-center">
        <h2 class="heading pt-3 pb-3" style="color:white;">Featured Jobs</h2>
            <div class="album py-5 bg-light">
                <div class="container">
                    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                        <div class="col">
                            <div class="card shadow-sm">
                                <img src="{% static 'img/2.jpg' %}" width=200 height=200 class="d-block w-100" alt="...">
                                <div class="card-body">
                                    <h2><u>Code Programmer</u></h2>
                                    <p class="card-text">Computer programmers write and test code that allows computer applications 
                                    and programs to function.Programming languages are necessary skills for computer programmers.</p>
                                </div>
                            </div>
                        </div>
                        <div class="col">
                            <div class="card shadow-sm">
                                <img src="{% static 'img/3.jpg' %}" width=200 height=200 class="d-block w-100" alt="...">
                                <div class="card-body">
                                    <h2><u>Web Developer</u></h2>
                                    <p class="card-text">Web developers creates websites. Generally they focus on front-end development,
                                     which involves designing sites and producing content, or back-end development to make features work.</p>
                                </div>
                            </div>
                        </div>
                        <div class="col">
                            <div class="card shadow-sm">
                                <img src="{% static 'img/4.jpg' %}" width=200 height=200 class="d-block w-100" alt="...">
                                <div class="card-body">
                                    <h2><u>Software Engineer</u></h2>
                                    <p class="card-text">Software engineers design software programs and often participate in the details
                                    of their development.They apply engineering principles and systematic methods to develop programs. </p>
                                </div>
                            </div>
                        </div>
</section>

{% endblock %}

{% block javascripts %}
<!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
{% endblock javascripts %}

templates/base.html
{% load static %}
<html lang="en">
  <head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">

    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">

    <!-- Font Awesome CSS for using icons added manually-->
    <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">

    <!-- Google fonts - Roboto for copy, Montserrat for headings-->
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,700">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Montserrat:400,700">

    <!-- owl carousel-->
    <link rel="stylesheet" href="{% static 'vendor/owl.carousel/assets/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/owl.carousel/assets/owl.theme.default.css' %}">

    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
    
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    
    {% block styles %}{% endblock %}

    <!-- Favicon-->
    <link rel="shortcut icon" href="favicon.png">

    <title> {% block title %}{% endblock title %} | Job Portal</title>
  </head>

<body>

<!-- navbar creation which will show in all pages-->
<header class="header">
    <nav class="navbar navbar-expand-lg bg-dark">
        <div class="container">
            <img src="{% static 'img/1.png' %}"  width=300 height=100 alt="logo" class="d-none d-lg-block">
            <button type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
                    class="navbar-toggler navbar-toggler-right">Menu<i class="fa fa-bars"></i>
            </button>
            <div id="navbarSupportedContent" class="collapse navbar-collapse">
                <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a href="/" class="nav-link">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a href="/about" class="nav-link">About Jobs</a>
                        </li>
                        <li class="nav-item">
                            <a href="/contact" class="nav-link">Contact Us</a>
                        </li>

                    <!--python code for the using the dropdowns menu and changing navabr wrt user-->
                    {% if request.user.is_authenticated and request.user.role == 'employer' %}
                        <li class="nav-item dropdown">
                            <a id="clientZone" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" 
                            class="nav-link dropdown-toggle has-img mb-3 mb-lg-0 mt-3 mt-lg-0">
                                <div class="client-menu-image">
                                    <div class="inner">
                                        <img src="{% static 'img/8.jpg' %}" alt="company image" class="img-fluid">
                                    </div>
                                </div>   
                                {% if request.user.role == 'employee' %}
                                    {{ request.user.first_name }} {{ request.user.last_name }}
                                {% else %}
                                    {{ request.user.first_name }}
                                {% endif %}
                            </a>
                            <div aria-labelledby="clientZone" class="dropdown-menu">
                                <a href="{% url 'JobWork:employer-dashboard' %}" class="dropdown-item">Dashboard</a>
                                <a href="{% url 'AccountsUser:logout' %}" class="dropdown-item">Logout</a>
                            </div>
                        </li>
                    {% elif request.user.is_authenticated and request.user.role == 'employee' %}
                        <li class="nav-item dropdown">
                            <a id="clientZone" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                               class="nav-link dropdown-toggle has-img mb-3 mb-lg-0 mt-3 mt-lg-0">
                                <div class="client-menu-image">
                                    <div class="inner">
                                        <img src="{% static 'img/7.png' %}" alt="company image" class="img-fluid">
                                    </div>
                                </div>   
                                {% if request.user.role == 'employee' %}
                                    {{ request.user.first_name }} {{ request.user.last_name }}
                                {% else %}
                                    {{ request.user.first_name }}
                                {% endif %}
                            </a>
                            <div aria-labelledby="clientZone" class="dropdown-menu">
                                <a href="/" class="dropdown-item">Search Jobs</a>
                                <a href="{% url 'AccountsUser:employer-profile-update' %}" class="dropdown-item">Edit Profile</a>
                                <a href="{% url 'AccountsUser:logout' %}" class="dropdown-item">Logout</a>
                            </div>
                        </li>
                    {% else %}
                        <li class="nav-item dropdown">
                            <a id="pages" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                               class="nav-link dropdown-toggle"><i class="fa fa-signing"></i> Register
                            </a>
                            <div aria-labelledby="pages" class="dropdown-menu">
                                <a href="{% url 'AccountsUser:employee-register' %}" class="dropdown-item">Employee</a>
                                <a href="{% url 'AccountsUser:employer-register' %}" class="dropdown-item">Employer</a>
                            </div>
                        </li>
                        <li class="nav-item" style="color: #fff">
                            <a href="{% url 'AccountsUser:login' %}" class="btn navbar-btn btn-outline-light mb-5 mb-lg-0">
                                <i class="fa fa-sign-in"></i> Login
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>

<!--for loop for displaying alert messages-->
<div>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                <strong>{{ message }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}
{% block content %} {% endblock %}
</div>

<!--footer-->
<!-- <footer class="footer">
    <div class="footer__copyright">
        <div class="container">
            <div class="row">
                <div class="col-md-6 text-md-left text-center">
                    <p>© Developed by </p>
                </div>
            </div>
        </div>
    </div>
</footer> -->


<!--various scripts used in for foem filling and various aspects-->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/popper.js/umd/popper.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %}"></script>
<script src="{% static 'vendor/owl.carousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap-select/js/bootstrap-select.min.js' %}"></script>
<script src="{% static 'js/front.js' %}"></script>


{% block javascripts %}{% endblock %}

</body>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Contact{% endblock %}

{% block content %}
<div class="container-fluid px-0">
<img src="{% static 'img/5.jpg' %}" width=800 height=250 class="d-block w-100" alt="contact logo">
</div>
<!--Creating contact form for taking query and displaying message-->
<div class="container mb-3 py-4">
    <form method="post" action="/contact">
        {% csrf_token %}
        <div class="form-group pt-4">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Enter your Name">
        </div>
        <div class="form-group pt-4">
            <label for="email">Email address</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Enter Your Email">
        </div>
        <div class="form-group pt-4">
            <label for="phone">Phone Number</label>
            <input type="phone" class="form-control" id="phone" name="phone" placeholder="Enter Your Phone Number">
        </div>      
        <div class="form-group pt-4 pb-4">
            <label for="desc">Describe the reason...</label>
            <textarea class="form-control" id="desc" rows="3" name="desc"></textarea>
        </div>
        <button class="btn btn-primary" type="submit">Submit</button>
    </form>
</div>

{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock %}

{% block content %}


<!--Creating section for making page attractive-->
    <section class="bg-success">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <div class="job-form-box" style="background-color:blue; opacity: 0.8;">
                        <h2 class="heading" style="color: white">Find a job that will fit to your expertise!!!</h2>
                        <form id="job-main-form" method="get" action="{% url 'JobWork:searh' %}" class="job-main-form">
                            <div class="controls" style="color: white;">
                                <div class="row align-items-center">
                                    <div class="col-md-5">
                                        <div class="form-group">
                                            <label for="profession">Position</label>
                                            <input type="text" id="profession" name="position"
                                                   placeholder="Position you are looking for" class="form-control" style="color: black">
                                        </div>
                                    </div>
                                    <div class="col-md-5">
                                        <div class="form-group">
                                            <label for="location">Location</label>
                                            <input type="text" id="location" name="location"
                                                   placeholder="Any particular location?" class="form-control">
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <button type="submit" class="btn btn-outline-white-primary job-main-form__button">
                                            <i class="fa fa-search"></i> 
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    
{% endblock %}

templates/intro.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Introduction{% endblock %}

{% block content %}
    <section class="bg-light-gray pt-0 pb-4">
        {% if request.user.is_authenticated and request.user.role == 'employer' %}
            <img src="{% static 'img/11.jpg' %}" width=700 height=250 class="d-block w-100" alt="hiring">
            <h1 class="heading pt-1 pb-1">Welcome,<font color="brown"> {{ request.user.first_name }} Company</font>
                <br>
                <small><font color="blue"><b>{{ request.user.last_name }}</b></font></small>
            </h1>
        {% elif request.user.is_authenticated and request.user.role == 'employee' %}
            <img src="{% static 'img/10.jpg' %}" width=700 height=250 class="d-block w-100" alt="vacancy">
            <h1 class="heading pt-4 pb-2">Welcome,<font color="brown"> {{ request.user.first_name }}
                 {{ request.user.last_name }}</font>
            </h1>
        {% endif %}
    </section>
    

{% endblock %}