JobPortal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('JobWork.urls')),
    path('', include('AccountsUser.urls')),
]

JobWork/urls.py
from django.urls import path, include
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = "JobWork"

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about', home.about,name='About'),
    path('contact', home.contact,name='Contact'),
    path('intro', home.intro,name='Intro'),
    path('search', SearchView.as_view(), name='searh'),
    path('employer/dashboard', include([
        path('', DashboardView.as_view(), name='employer-dashboard'),
        path('applicants/<int:job_id>', ApplicantPerJobView.as_view(), name='employer-dashboard-applicants'),
        path('delete/<int:job_id>/', delete_view, name='employer-dashboard-delete'),

    ])),
    path('apply-job/<int:job_id>', ApplyJobView.as_view(), name='apply-job'),
    path('jobs/<int:id>', JobDetailsView.as_view(), name='jobs-detail'),
    path('employer/jobs/create', JobCreateView.as_view(), name='employer-jobs-create'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/jobs/create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Post New Job
{% endblock %}

{% block content %}

    <section class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h1 class="heading">Add a new Position</h1>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger alert-dismissable">
                                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                    <strong>{{ field.name }} {{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                        {% endfor %}
                    {% endif %}
                    <form id="job-main-form" method="post" action="" class="job-add-form">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-lg-12">
                                <h4>Job details</h4>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12 form-group">
                                <label for="title">Job Title</label>
                                <input id="title" name="title" type="text" class="form-control">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12 form-group">
                                <label for="text">Job Description</label>
                                <textarea id="text" name="description" rows="5" class="form-control"></textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6 form-group">
                                <label for="company_name">Company Name</label>
                                <input id="company_name" name="company_name" type="text" class="form-control" value="{{ form.company_name.value|default_if_none:"" }}">
                            </div>
                            <div class="col-lg-6 form-group">
                                <label for="location">Location</label>
                                <input id="location" name="location" type="text" placeholder="e.g. Pune" class="form-control">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6 form-group">
                                <label for="category">Category</label>
                                <select id="category" name="category" placeholder="Choose category" class="form-control">
                                    <option value="Programmer">Programmer</option>
                                    <option value="Developer">Developer</option>
                                    <option value="Analyst">Analyst</option>
                                    <option value="Database Administrator">Database Administrators</option>
                                </select>
                            </div>
                            <div class="col-lg-6 form-group">
                                <label for="type">Type</label>
                                <select id="type" name="type" placeholder="Choose job type" class="form-control">
                                    <option value="1">Full time</option>
                                    <option value="2">Internship</option>
                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xl-6 form-group">
                                <label for="salary">Salary</label>
                                <input id="salary" name="salary" type="text" placeholder="e.g. 6 LPA" class="form-control">
                            </div>
                            <div class="col-xl-6 form-group">
                                <label for="validity">Validity of the post</label>
                                <input id="validity" name="last_date" type="date" class="form-control" value="{{ form.last_date.value|default_if_none:"" }}">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12 text-center pt-2 mt-2">
                                <button type="submit" class="btn btn-success"><i class="fa fa-magic"></i>
                                    Save and publish
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/jobs/details.html
{% extends 'base.html' %}
{% load static %}
{% load is_already_applied %}
{% block title %}
    Job Details
{% endblock %}

{% block content %}
<!--different sections for making pages attractive-->
    <section class="bg-light-gray">
        <div class="container">
            <h1 class="heading"><font color="brown">{{ job.title }}</font><br>
                <small> at <font color="blue"><b>{{ job.company_name }}</b></font></small>
            </h1>
            <div class="job-detail-description"><i class="fa fa-map-marker job__location"> </i>
                <b>{{ job.location }}</b> |
                {% if job.type == '1' %}
                    <span class="badge featured-badge badge-success">Full time</span>
                {% else %}
                    <span class="badge featured-badge badge-warning">Internship</span>
                {% endif %}
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <h3>Category: {{ job.category }}</h3>
                    <h5>Last date: {{ job.last_date|date }}</h5>
                    <h5 class="text-info">Salary: {{ job.salary }}</h5>
                    <blockquote class="blockquote">
                        <p>{{ job.description }}</p>
                    </blockquote>
                    <div class="job-detail__apply-bottom">
                        {% if request.user.is_authenticated and request.user.role == 'employee' %}
                            {% is_already_applied job request.user as is_applied %}
                            {% if is_applied %}
                                <input type="button" class="btn btn-info" value="Already applied"/>
                            {% else %}
                                <form action="{% url 'JobWork:apply-job' job.id %}" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="job" value="{{ job.id }}">
                                    <input type="submit" class="btn btn-success" value="Apply for this job"/>
                                </form>
                            {% endif %}
                        {% elif request.user.is_authenticated and request.user.role == 'employer' %}
                        {% else %}
                            <form action="{% url 'JobWork:apply-job' job.id %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="job" value="{{ job.id }}">
                                <input type="submit" class="btn btn-success" value="Apply for this job"/>
                            </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/jobs/search.html
{% extends 'base.html' %}
{% load static %}
{% block title %} All jobs Search {% endblock %}

{% block content %}
    <section>
        <div class="container">
            <h3 class="heading">We have found <span class="accent">{{ jobs.count }}</span> Jobs</h3>

            <!--for loop for displaying jobs-->
            {% for job in jobs %}
                <div class="job-listing  ">
                    <div class="row">
                        <div class="col-md-12 col-lg-6">
                            <div class="row">
                                <div class="col-2">
                                    <img src="{% static 'img/8.jpg' %}" width=300 height=300 alt="Ipsioou " class="img-fluid">
                                </div>
                                <div class="col-10">
                                    <h4 class="job__title"><a href="{% url 'JobWork:jobs-detail' job.id %}">{{ job.title }}</a></h4>
                                    <h5><p class="job__company"> {{ job.company_name }} </p></h5>
                                </div>
                            </div>
                        </div>
                        <div class="col-10 col-md-3 col-lg-2 ml-auto"><i class="fa fa-map-marker job__location"></i>
                            <b>{{ job.location }}</b>
                        </div>
                        <div class="col-10 col-md-3 col-lg-3 ml-auto">
                            <p><b>Posted {{ job.created_at|timesince }} Ago</b></p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </section>

{% endblock %}